testrun/urls.py
from django.conf.urls import url

from . import views

app_name = 'testrun'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<transaction_pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<transaction_pk>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<transaction_pk>[0-9]+)/transaction_edit/$', views.transaction_edit, name='transaction_edit'),
   	url(r'^transaction_create/$',views.transaction_create, name='transaction_create'),
   	url(r'^search_amount/$',views.search_amount, name='search_amount'),
    url(r'^search_card_type/$',views.search_card_type, name='search_card_type'),
    url(r'^search_supplier/$',views.search_supplier, name='search_supplier'),
    url(r'^search_client/$',views.search_client, name='search_client'),
    url(r'^search_staff/$',views.search_staff, name='search_staff'),
   	url(r'^card/$',views.card, name='card'),
   	url(r'^card_add/$',views.card_add, name='card_add'),
   	url(r'^(?P<card_pk>[0-9]+)/card_delete/$',views.card_delete, name='card_delete'),
   	url(r'^client/$',views.client, name='client'),
   	url(r'^client_add/$',views.client_add, name='client_add'),
   	url(r'^(?P<client_pk>[0-9]+)/client_delete/$',views.client_delete, name='client_delete'),
   	url(r'^staff/$',views.staff, name='staff'),
   	url(r'^staff_add/$',views.staff_add, name='staff_add'),
   	url(r'^(?P<staff_pk>[0-9]+)/staff_delete/$',views.staff_delete, name='staff_delete'),

]

testrun/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.http import HttpResponseRedirect
# Create your models here.
class Transaction(models.Model):
	date_created = models.DateTimeField(default=timezone.now())
	date_transaction = models.CharField(max_length=200,default='dd/mm/yy' )
	card_type = models.CharField(max_length=200)
	supplier = models.CharField(max_length=200)
	purchase_details = models.CharField(max_length=255)
	amount = models.DecimalField(max_digits=99999999,decimal_places=2)
	GST = models.CharField(max_length=100,default='inc GST')
	client = models.CharField(max_length=255)
	wfm_job_number = models.CharField(max_length=255,default='001')
	staff = models.CharField(max_length=255,default='')
	notes = models.TextField()
	processed = models.BooleanField(default=False)

	   

	def __str__(self):
		if self.processed == True:
			process = 'Processed'
		else:	
			process = ''

		return "{} -- {} -- {} -- {} -- ${} -- {} -- {} ".format(
													 self.date_created.strftime("%d/%m/%Y"),
													 self.card_type,
													 self.supplier,
													 self.purchase_details,
													 self.amount,
													 self.staff,
													 process)


class Card_Type(models.Model):		
		type = models.CharField(max_length=200)



		def __str__(self):
			return "{}" .format(self.type)


class Client(models.Model):		
		client = models.CharField(max_length=200)
		client_name = models.CharField(max_length=200,default='')



		def __str__(self):
			return "{}" .format(self.client)

class Staff(models.Model):		
		staff = models.CharField(max_length=200)
		staff_name = models.CharField(max_length=200, default='')



		def __str__(self):
			return "{}" .format(self.staff)

testrun/forms.py
from django import forms

from . import models


class TransactionForm(forms.ModelForm):
    class Meta:
        model = models.Transaction
        #date_created = forms.TextInput(attrs={'disabled':'disabled'})
        fields = [
        	'date_created',
			'date_transaction', 
			'card_type', 
			'supplier', 
			'purchase_details', 
			'amount',  
			'GST', 
			'client',
			'wfm_job_number',
			'staff', 
			'notes', 
			'processed' 
        ]

        def __init__(self, *args, **kwargs):
        	super(TransactionForm, self).__init__(*args, **kwargs)
        	instance = getattr(self, 'instance', None)
        	if instance and instance.pk:
       			self.fields['date_created'].widget.attrs['disabled'] = True

testrun/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from . import forms
from . import models
from .models import Transaction
from .models import Card_Type
from .models import Client
from .models import Staff
import time
import datetime
from django.utils import timezone

def index(request):
    latest_transaction_list = Transaction.objects.order_by('-date_created')
    #template = loader.get_template('testrun/index.html')
    #output = ''',\r\n '''.join([str(t) for t in latest_transaction_list])
    context = {'latest_transaction_list': latest_transaction_list,}
    return render(request, 'testrun/index.html', context)


def client(request):
    client_list = Client.objects.all()

    context = {'client_list': client_list,}
    return render(request, 'testrun/client.html', context)

def client_add(request):
    client = models.Client()

    if request.POST['client']:
        client.client_name = request.POST['client']
        client.save()

    client_list = Client.objects.all()
    context = {'client_list': client_list,}    

    return render(request, 'testrun/client.html', context)   

def client_delete(request, client_pk=0):
    client= get_object_or_404(models.Client, pk=client_pk)
    client.delete()

    client_list = Client.objects.all()
    context = {'client_list': client_list,}    

    return render(request, 'testrun/client.html', context)

def card(request):
    card_list = Card_Type.objects.all()

    context = {'card_list': card_list,}
    return render(request, 'testrun/card.html', context) 

def card_add(request):
    card = Card_Type()

    if request.POST['card']:
        card.type = request.POST['card']
        card.save()

    card_list = Card_Type.objects.all()
    context = {'card_list': card_list,}    

    return render(request, 'testrun/card.html', context)

def card_delete(request, card_pk=0):
    card = get_object_or_404(models.Card_Type, pk=card_pk)
    card.delete()

    card_list = Card_Type.objects.all()
    context = {'card_list': card_list,}    

    return render(request, 'testrun/card.html', context)



def staff(request):    
    staff_list = Staff.objects.all()

    context = {'staff_list': staff_list,}
    return render(request, 'testrun/staff.html', context) 

def staff_add(request):
    staff = Staff()

    if request.POST['staff']:
        staff.staff_name = request.POST['staff']
        staff.save()

    staff_list = Staff.objects.all()

    context = {'staff_list': staff_list,}  

    return render(request, 'testrun/staff.html', context)


def staff_delete(request, staff_pk=0):
    staff = get_object_or_404(models.Staff, pk=staff_pk)
    staff.delete()

    staff_list = Staff.objects.all()
    context = {'staff_list': staff_list,}    

    return render(request, 'testrun/staff.html', context)

def search_amount(request):	
	if request.POST['search_amount']:
		value = request.POST['search_amount']
		latest_transaction_list = Transaction.objects.filter(amount__contains=value)
	else:
		latest_transaction_list = Transaction.objects.order_by('-date_created')	

	context = {'latest_transaction_list': latest_transaction_list,}
	return render(request, 'testrun/index.html', context)

def search_card_type(request): 
    if request.POST['search_card_type']:
        value = request.POST['search_card_type']
        latest_transaction_list = Transaction.objects.filter(card_type__contains=value).order_by('-date_created') 
    else:
        latest_transaction_list = Transaction.objects.order_by('-date_created') 

    context = {'latest_transaction_list': latest_transaction_list,}
    return render(request, 'testrun/index.html', context)

def search_supplier(request): 
    if request.POST['search_supplier']:
        value = request.POST['search_supplier']
        latest_transaction_list = Transaction.objects.filter(supplier__contains=value).order_by('-date_created') 
    else:
        latest_transaction_list = Transaction.objects.order_by('-date_created') 

    context = {'latest_transaction_list': latest_transaction_list,}
    return render(request, 'testrun/index.html', context)

def search_client(request): 
    if request.POST['search_client']:
        value = request.POST['search_client']
        latest_transaction_list = Transaction.objects.filter(client__contains=value).order_by('-date_created') 
    else:
        latest_transaction_list = Transaction.objects.order_by('-date_created') 

    context = {'latest_transaction_list': latest_transaction_list,}
    return render(request, 'testrun/index.html', context) 

def search_staff(request): 
    if request.POST['search_staff']:
        value = request.POST['search_staff']
        latest_transaction_list = Transaction.objects.filter(staff__contains=value).order_by('-date_created') 
    else:
        latest_transaction_list = Transaction.objects.order_by('-date_created') 

    context = {'latest_transaction_list': latest_transaction_list,}
    return render(request, 'testrun/index.html', context)          


def detail(request, transaction_pk):
	transaction = get_object_or_404(Transaction, pk=transaction_pk)
	return render(request, 'testrun/detail.html', {'transaction': transaction})
    #return HttpResponse("You're looking at transaction %s." % transaction_id)    

def results(request, transaction_pk):
	transaction = get_object_or_404(Transaction, pk=transaction_pk)
	
	try:
		if request.POST['processed'] == 'True':
			transaction.processed = True
		else:
			transaction.processed = False
	except:
		transaction.processed = False
		transaction.save()
		
	else:	
		transaction.save()
	#response = "You're looking at the results of transaction %s."
	latest_transaction_list = Transaction.objects.filter(pk=transaction_pk)
	context = {'latest_transaction_list': latest_transaction_list,}
	return render(request, 'testrun/index.html', context)


def transaction_edit(request, transaction_pk=0):
    transaction = get_object_or_404(models.Transaction, pk=transaction_pk)
    card_list = Card_Type.objects.all()
    client_list = Client.objects.all()
    staff_list = Staff.objects.all()
    form = forms.TransactionForm()
    
    if request.method == 'POST':
        form = forms.TransactionForm(request.POST, instance=transaction)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Transaction added!")
            return HttpResponseRedirect(reverse('testrun:transaction_edit', kwargs={
                'transaction_pk': transaction_pk,  }))
    return render(request, 'testrun/transaction_edit.html', {'form': form, 
                                                             'transaction' : transaction, 
                                                             'card_list' : card_list, 
                                                             'client_list' : client_list,
                                                             'staff_list' : staff_list
                                                             }) 	


def transaction_create(request):
    
    transaction = models.Transaction
    card_list = Card_Type.objects.all()
    client_list = Client.objects.all()
    staff_list = Staff.objects.all()
    form = forms.TransactionForm()
    form.fields['date_created'].widget.attrs['readonly'] = True
    date_value =  timezone.now()
    
    if request.method == 'POST':
        form = forms.TransactionForm(request.POST)
        if form.is_valid():
            transact = form.save(commit=False)
            transact.transaction = transaction
            #transact.date_created = timezone.now()
            transact.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Transaction added!")
            return HttpResponseRedirect(reverse('testrun:transaction_create'))
    return render(request, 'testrun/transaction_form.html', {'form': form, 
                                                             'transaction' : transaction,
                                                             'card_list' : card_list, 
                                                             'client_list' : client_list,
                                                             'staff_list' : staff_list,
                                                             'date_value' : date_value
                                                             }) 

testrun/templates/testrun/detail.html
<a href="{% url 'testrun:index' %}"> <--Back to list </a>


<h1> {{ transaction.pk }} ${{ transaction.amount }} </h1>

<h1> Processed </h1>
 
   

testrun/templates/testrun/index.html
{% extends "testrun/layout.html" %}

{% block content %}
<h2>List of transactions </h2>
<p><a href="{% url 'testrun:transaction_create' %}"> Make new Transaction </a></p>
<table>
 <tr>
<td>
<p><form method="POST" action="{% url 'testrun:search_amount' %}" >
		{% csrf_token %}
		<input type="submit" value="Search Amount" /><input type="text" name="search_amount"  >		
</form></p></td>

<td><p><form method="POST" action="{% url 'testrun:search_card_type' %}" >
        {% csrf_token %}
        <input type="submit" value="Search Card Type" /><input type="text" name="search_card_type"  >     
</form></p></td>

<td><p><form method="POST" action="{% url 'testrun:search_supplier' %}" >
        {% csrf_token %}
        <input type="submit" value="Search Supplier" /><input type="text" name="search_supplier"  >     
</form></p></td>

<td><p><form method="POST" action="{% url 'testrun:search_client' %}" >
        {% csrf_token %}
        <input type="submit" value="Search Client" /><input type="text" name="search_client"  >     
</form></p></td>

<td><p><form method="POST" action="{% url 'testrun:search_staff' %}" >
        {% csrf_token %}
        <input type="submit" value="Search Staff" /><input type="text" name="search_staff"  >     
</form></p></td></tr>
</table>

{% if latest_transaction_list %}

    <table>
    <tr>
    <th>Date created</th>
    <th>Transaction date</th>
    <th><a style="color:blue;" href="{% url 'testrun:card' %}">Card Type</a></th>
    <th>Supplier</th>
    <th>Details</th>
    <th>Amount</th>
    <th><a style="color:blue;" href="{% url 'testrun:client' %}">Client</a></th>
    <th>WFM Job Number</th>
    <th><a style="color:blue;" href="{% url 'testrun:staff'  %}">Staff</a></th>
    <th>Notes</th>
    <th>Processed (Accounts Use Only)</th>
    </tr>
     {% for transaction in latest_transaction_list %}

       {% if transaction.processed == True %}
       	<tr>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.date_created   }}</a></td>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.date_transaction   }}</a></td>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.card_type }}</a></td>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.supplier }}</a></td>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.purchase_details }}</a></td>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.amount }} {{ transaction.GST }}</a></td>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.client }}</a> </td>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.wfm_job_number  }} </a></td>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.staff  }} </a></td>
        <td><a style="color:red;" href="{% url 'testrun:detail' transaction.id %}">{{ transaction.notes   }} </a></td>
        <td>
        	<form action="{% url 'testrun:results' transaction.id %}" method="post" >
				{% csrf_token %}
				{% if transaction.processed == True %}
					<input type="checkbox" name="processed" value='True' checked>
				{% else %}
					<input type="checkbox" name="processed" value='True'  >	
				{%endif%}	
					
				
				<label> 
					{% if transaction.processed == True %} Yes
					{% else %} No
					{%endif%}	

				<input type="submit" value="Process" />	
							
				</label>
			</form>
        </td>	
        </tr>
        {% else %}
        <tr>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.date_created }}</a></td>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.date_transaction }}</a></td>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.card_type }}</a></td>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.supplier }}</a></td>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.purchase_details }}</a></td>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.amount}} {{ transaction.GST}} 
         </a></td>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.client }}</a> </td>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.wfm_job_number }} </a></td>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.staff }} </a></td>
        <td><a href="{% url 'testrun:transaction_edit' transaction.id %}" class="process">{{ transaction.notes  }} </a></td>
        <td>
        	<form action="{% url 'testrun:results' transaction.id %}" method="post" >
				{% csrf_token %}
				{% if transaction.processed == True %}
					<input type="checkbox" name="processed" value='True' checked>
				{% else %}
					<input type="checkbox" name="processed" value='True'  >	
				{%endif%}	
					
				
				<label> 
					{% if transaction.processed == True %} Yes
					{% else %} No
					{%endif%}	

				<input type="submit" value="Process" />	
							
				</label>
			</form>
        </td>	


        </tr>
        {%endif%}
	  {% endfor %}	
    </table>
    
{% else %}
    <p>No transactions are available.</p>
{% endif %}

{% endblock %}

testrun/templates/testrun/transaction_edit.html
{% extends "testrun/layout.html" %}

{% block content %}
<a href="{% url 'testrun:index' %}"> <--Back to list </a>

   
        <h2> Transaction {{ transaction.id }} </h2>

        <form method="POST" action="{% url 'testrun:transaction_edit' transaction_pk=transaction.id %}" class="form-style-1">
         {% csrf_token %}
            <table width="25%">

            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Date Created:</label></td>
                <td>{{ form.date_created }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Transaction Date:</label></td>
                <td><input  id="id_date_transaction" type="text" name= "date_transaction"  value="{{ transaction.date_transaction}}" /></td>
            </tr> 

           <tr>
              <td><label for="{{ form.subject.id_for_label }}">Card Type:</label></td>
                <td><select name="card_type">
                    {% for card in card_list %} 
                    {% if card.type == transaction.card_type %}
                        <option value="{{ card.type }}" selected>{{ card.type }}</option>   
                    {%else%}
                        <option value="{{ card.type }}" >{{ card.type }}</option>      
                    {%endif%}   
                    {% endfor %}   
                    <select>  

                </td>
            </tr> 

            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Supplier:</label></td>
                <td><input id="id_supplier" type="text" name="supplier"  value="{{transaction.supplier}}" /></td>
            </tr>
            <tr> 
                <td><label for="{{ form.subject.id_for_label }}">Purchase Details:</label></td>
                <td><input id="id_purchase_details" type="text" name="purchase_details"  value="{{transaction.purchase_details}}" /></td>
            </tr> 
             
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Amount:</label></td>
                <td><input id="id_amount" type="text"  name="amount" value="{{transaction.amount}}" /></td>
            </tr>
                
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">GST:</label></td>
                  <td><select name="GST">  
                    {% if transaction.client == 'ex GST' %}        
                      <option value="ex GST" selected>Ex Gst</option>
                      <option value="inc GST" >Inc Gst</option>
                    {% else %}
                      <option value="ex GST" >Ex Gst</option>
                      <option value="inc GST" selected>Inc Gst</option>
                    {%endif%}    

                </select>
                </td>
            </tr> 
            
           <tr>    
                <td><label for="{{ form.subject.id_for_label }}">Client:</label></td>
                 <td><select name="client">

                        <option value="{{ transaction.client }}" selected>{{ transaction.client  }}</option>  
                    {% for client in client_list %} 
                    {% if client.client == transaction.client %}
                        <option value="{{ client.client_name}}" selected>{{ client.client_name }}</option>   
                    {%else%}
                        <option value="{{ client.client_name }}" >{{ client.client_name }}</option>      
                    {%endif%}   
                    {% endfor %}   
                    <select>  

                </td>
              
              
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Wfm Job Number</label></td>
                <td><input id="id_wfm_job_number" type="text" name="wfm_job_number" value="{{transaction.wfm_job_number}}" /></td>
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Staff:</label></td>
                   <td><select name="staff">
                    <option value="{{ transaction.staff }}" selected>{{ transaction.staff }}</option> 
                    {% for staff in staff_list %} 
                    {% if staff.staff == transaction.staff %}
                        <option value="{{ staff.staff_name}}" selected>{{ staff.staff_name }}</option>   
                    {%else%}
                        <option value="{{ staff.staff_name }}" >{{ staff.staff_name }}</option>      
                    {%endif%}   
                    {% endfor %}   
                    <select>  

                </td>
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Notes:</label></td>
                <td><textarea id="id_notes"  name="notes" >{{ transaction.notes }}</textarea></td>
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Processed:</label></td>
                <td>{% if transaction.processed == True %}
                         <input type="checkbox" name="processed" value='True' checked>
                    {% else %}
                         <input type="checkbox" name="processed" value='True'  > 
                    {%endif%}   </td>
            </tr>
            <tr>
                <td> </td>
                <td> <input type="submit" class="button" value="Save" align="center"></td>
            </tr> 
            </table>
        </form>


{% endblock %}

testrun/templates/testrun/transaction_edit2.html
{% extends "testrun/layout.html" %}

{% block content %}
<a href="{% url 'testrun:index' %}"> <--Back to list </a>

   
        <h2> Transaction {{ transaction.id }} </h2>
        <form method="POST" action="{% url 'testrun:transaction_edit' transaction_pk=transaction.id %}" class="form-style-1">
            {% csrf_token %}
            <table width="25%">

            <tr>
            	<td><label for="{{ form.subject.id_for_label }}">Date:</label></td>
          		<td><input id="id_date" type="text" name="date"  value="{{transaction.date}}" /></td>
            </tr>
            <tr>
            	<td><label for="{{ form.subject.id_for_label }}">Card Type:</label></td>
            	<td><input id="id_card_type" type="text" name="card_type" value="{{transaction.card_type}}" /></td>
            </tr>
             <tr>
            	<td><label for="{{ form.subject.id_for_label }}">Company:</label></td>
            	<td><input id="id_company" type="text" name="company"  value="{{transaction.company}}" /> </td>
            </tr>
                <tr>
            	<td><label for="{{ form.subject.id_for_label }}">Purchase Details:</label></td>
            	<td><input id="id_purchase_details" type="text" name="company"  value="{{transaction.purchase_details}}" /></td>
            </tr>
             </tr>
                <tr>
            	<td><label for="{{ form.subject.id_for_label }}">Notes:</label></td>
            	<td><textarea id="id_notes"  name="company" >{{transaction.notes}}</textarea></td>
            </tr>
                 </tr>
                <tr>
            	<td><label for="{{ form.subject.id_for_label }}">Client:</label></td>
            	<td><input id="id_client" type="text" name="client"  value="{{transaction.client}}" /></td>
            </tr>
            </tr>
                <tr>
            	<td><label for="{{ form.subject.id_for_label }}">GST:</label></td>
            	<td><input id="id_GST" type="text" name="client"  value="{{transaction.GST}}" /></td>
            </tr>
            </tr>
                <tr>
            	<td><label for="{{ form.subject.id_for_label }}">Amount:</label></td>
            	<td><input id="id_amount" type="text" name="client"  value="{{transaction.amount}}" /> </td>
            </tr>
            </tr>
                <tr>
            	<td><label for="{{ form.subject.id_for_label }}">Staff:</label></td>
            	<td><input id="id_staff" type="text" name="staff"  value="{{transaction.staff}}" />  </td>
            </tr>
			<tr>
            	<td><label for="{{ form.subject.id_for_label }}">Comments:</label></td>
            	<td><textarea id="id_comments"  name="comments" >{{transaction.comments}}</textarea></td>
            </tr>
            <tr>
            	<td><label for="{{ form.subject.id_for_label }}">Processed:</label></td>
            	<td><input id="processed" type="text" name="processed" value="{{transaction.processed}}"> </td>
            </tr>
            <tr>
            	<td> </td>
            	<td> <input type="submit" class="button" value="Save" align="center"></td>
           
            </tr>
    		</table>
        </form>


{% endblock %}
   

testrun/templates/testrun/transaction_edit3.html
{% extends "testrun/layout.html" %}

{% block content %}
<a href="{% url 'testrun:index' %}"> <--Back to list </a>

   
        <h2> Transaction {{ transaction.id }} </h2>

        <form method="POST" action="{% url 'testrun:transaction_edit' transaction_pk=transaction.id %}" class="form-style-1">
         {% csrf_token %}
            <table width="25%">

            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Date Created:</label></td>
                <td>{{ form.date_created }}</td>
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Transaction Date:</label></td>
                <td><input  id="id_date_transaction" type="text" name= "date_transaction"  value="{{ transaction.date_transaction}}" /></td>
            </tr> 



            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Card Type:</label></td>
                <td><input id="id_card_type" type="text" name="card_type" value="{{transaction.card_type}}" /></td>
            </tr>
           <!--<tr>
              <td><label for="{{ form.subject.id_for_label }}">Card Type:</label></td>
                <td><select name="card_type">
                    {% for card in card_list %} 
                    {% if card.type == transaction.card_type %}
                        <option value="{{ card.type }}" selected>{{ card.type }}</option>   
                    {%else%}
                        <option value="{{ card.type }}" >{{ card.type }}</option>      
                    {%endif%}   
                    {% endfor %}   
                    <select>  

                </td>
            </tr> -->

            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Supplier:</label></td>
                <td><input id="id_supplier" type="text" name="supplier"  value="{{transaction.supplier}}" /></td>
            </tr>
            <tr> 
                <td><label for="{{ form.subject.id_for_label }}">Purchase Details:</label></td>
                <td><input id="id_purchase_details" type="text" name="purchase_details"  value="{{transaction.purchase_details}}" /></td>
            </tr> 
             
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Amount:</label></td>
                <td><input id="id_amount" type="text"  name="amount" value="{{transaction.amount}}" /></td>
            </tr>
                
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">GST:</label></td>
                <td><select name='GST'>  
                    {% if transaction.GST == 'ex GST' %}        
                      <option value="ex GST" selected>Ex Gst</option>
                      <option value="inc GST" >Inc Gst</option>
                    {% else %}
                      <option value="ex GST" >Ex Gst</option>
                      <option value="inc GST" selected>Inc Gst</option>
                    {%endif%}    

                </select>
                </td>
            </tr> 
            
            <tr>    
                <td><label for="{{ form.subject.id_for_label }}">Client:</label></td>
                <td><input id="id_GST" type="text" name="client"  value="{{transaction.client}}" /></td>
              
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Wfm Job Number</label></td>
                <td><input id="id_wfm_job_number" type="text" name="wfm_job_number" value="{{transaction.wfm_job_number}}" /></td>
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Staff:</label></td>
                <td><input id="id_staff" type="text" name="staff"  value="{{transaction.staff}}" /> </td>
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Notes:</label></td>
                <td><textarea id="id_notes"  name="notes" >{{ transaction.notes }}</textarea></td>
            </tr>
            <tr>
                <td><label for="{{ form.subject.id_for_label }}">Processed:</label></td>
                <td>{% if transaction.processed == True %}
                         <input type="checkbox" name="processed" value='True' checked>
                    {% else %}
                         <input type="checkbox" name="processed" value='True'  > 
                    {%endif%}   </td>
            </tr>
            <tr>
                <td> </td>
                <td> <input type="submit" class="button" value="Save" align="center"></td>
            </tr> 
            </table>
        </form>


{% endblock %}
   